# Generated by Django 4.1 on 2024-07-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreminder',
            name='NTY',
            field=models.BooleanField(default=False),
        ),
    ]
